language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install flake8 && flake8 .

script:
  # pytest --verbose -s  (print stdouts, etc.)
  - PYTEST_ADDOPTS="-s" python setup.py test
  - pip install .
